import { Router } from 'express';
import { articleController, articleInteractionController, uploadController } from '../factories/controllers.factory';
import { requireAuth } from '../middlewares/auth.middleware';
import { validateBody, validateParams } from '../middlewares/validate.middleware';
import { articleIdSchema, createArticleRequestSchema, updateArticleRequestSchema } from '../validators/article.validator';
import { articleInteractionRequestSchema } from '../validators/article-interaction.validator';
import { uploadImageMiddleware } from '../middlewares/upload.middleware';
const router = Router();
router.use(requireAuth);
router.get('/', articleController.getArticles);
router.get('/feed', articleController.getPersonalizedFeed);
router.get('/my', articleController.getMyArticles);
router.post('/upload-image', uploadImageMiddleware.array('images', 5), uploadController.uploadArticleImage);
router.get('/blocked', articleInteractionController.getBlocked);
router.get('/:id', validateParams(articleIdSchema.shape.params), articleController.getArticleById);
router.post('/', validateBody(createArticleRequestSchema.shape.body), articleController.createArticle);
router.put('/:id', validateParams(updateArticleRequestSchema.shape.params), validateBody(updateArticleRequestSchema.shape.body), articleController.updateArticle);
router.post('/:id/interaction', validateParams(articleInteractionRequestSchema.shape.params), validateBody(articleInteractionRequestSchema.shape.body), articleInteractionController.interact);
router.delete('/:id/interaction', validateParams(articleIdSchema.shape.params), articleInteractionController.remove);
router.delete('/:id', validateParams(articleIdSchema.shape.params), articleController.deleteArticle);
export default router;
 