import { Router } from 'express';
import { userController } from '../factories/controllers.factory';
import { requireAuth } from '../middlewares/auth.middleware';
import { validateBody } from '../middlewares/validate.middleware';
import { updatePasswordSchema, updatePreferencesSchema, updateProfileSchema } from '../validators/user.validator';
const router = Router();
router.use(requireAuth);
router.get('/profile', userController.getProfile);
router.put('/profile', validateBody(updateProfileSchema), userController.updateProfile);
router.put('/password', validateBody(updatePasswordSchema), userController.updatePassword);
router.put('/preferences', validateBody(updatePreferencesSchema), userController.updatePreferences);
export default router;
